upstream app_servers {
    zone app_servers 64k;
    server cloud-loadbalancer-lab-app-1:5000;
    server cloud-loadbalancer-lab-app-2:5000;
    server cloud-loadbalancer-lab-app-3:5000;
}

server {
    listen 80;

    location / {
        proxy_pass http://app_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}